services:

  nginx_web:
    build: ./front-end/
    ports:
      - "9000"
    depends_on:
      - flask_api

  flask_api:
    build: ./back-end/
    ports:
      - "5252"

  nginx_proxy:
      build: ./proxy/
      ports:
        - "80:80"
